### ISSUE TITLE
TypeBox Optimization

### ISSUE THREAD

**Issue by sinclairzx81** [decs/typeschema#10]
@decs Hi, cool project :)

Hey, had just noticed TB got added to the supported list (which is awesome, thanks!). Was just looking over the implementation of the TB compiler though, and note there might be a couple of optimizations you could implement there to help ensure good validation performance. Was looking specifically at the following lines https://github.com/decs/typeschema/blob/main/src/adapters/typebox.ts#L36-L48

```typescript
validate: async data => {
  const {TypeCompiler} = await import('@sinclair/typebox/compiler');
  const result = TypeCompiler.Compile(schema); // quite slow per validation pass
  if (result.Check(data)) {
    return {data};
  }
  return {
    issues: [...result.Errors(data)].map(
      ({message, path}) => new ValidationIssue(message, [path]),
    ),
  };
},
```
Two options for optimization below.

### Value.Check
  
You can use the `Value` module to perform dynamic type checking against a value. This isn't as fast as the compiled version, but would be faster than compiling the schematics each time `.validate(data)` is run. The `Value.Check` performance is roughly inline with Zod.
  
```typescript
validate: async data => {
  const {Value} = await import('@sinclair/typebox/value');
  if (Value.Check(schema, data)) {
    return {data};
  }
  return {
    issues: [...Value.Errors(schema, data)].map(
      ({message, path}) => new ValidationIssue(message, [path]),
    ),
  };
},
```
  
### Cache by Schema
  
Another approach you can maybe try is to cache the compiled `result` by schema reference. This caching pattern is an alternative to closure caching (where you have the outer closure compile, and return a validate function), but can be used to retain previously compiled compilation and only incurs a cost of a single `Map` lookup.

```typescript
const cache = new Map<TSchema, TypeCheck<any>>() // caches by reference

// ... 

validate: async data => {
  const {TypeCompiler} = await import('@sinclair/typebox/compiler');
  const result = cache.has(schema) ? cache.get(schema)! : (function() {
     const typecheck = TypeCompiler.Compile(schema);
     cache.set(schema, typecheck) // cache for next time.
     return typecheck
  }())
  if (result.Check(data)) {
    return {data};
  }
  return {
    issues: [...result.Errors(data)].map(
      ({message, path}) => new ValidationIssue(message, [path]),
    ),
  };
},
```
TypeBox supports both dynamic and compiled type checking. The decision to use one over the other mostly comes down to whether or not the environment is supportive of JIT compilation. For validation that runs everywhere, use `Value.Check`, for high performance where you have control over the environment, use the `TypeCompiler`.

Hope this helps, and great work. This project looks cool
Cheers
S

**Comment by decs** [comment]
Hey, @sinclairzx81!

Thanks a lot for the suggestions! I added a benchmark check for the typebox adapter and indeed saw a huge perf improvement by going with the cache approach.
We wrap the original schema with the `wrap()` function, which is already cached. I just moved the `TypeCompiler` call from `validate()` to `wrap()` and now the compiled type gets reused on every validation check

#### Before

```bash
deco@deco-mbp typeschema % yarn ts-node src/__tests__/benchmarks/typebox.ts
yarn run v1.22.19
$ /Users/deco/typeschema/node_modules/.bin/ts-node src/__tests__/benchmarks/typebox.ts
Running "typebox with valid data" suite...
Progress: 100%

  directly:
    6 038 584 ops/s, ±0.82%   | fastest

  through TypeSchema:
    266 288 ops/s, ±4.12%     | slowest, 95.59% slower

Running "typebox with invalid data" suite...
Progress: 100%

  directly:
    5 970 250 ops/s, ±0.12%   | fastest

  through TypeSchema:
    257 170 ops/s, ±3.56%     | slowest, 95.69% slower

✨  Done in 25.62s.
```

#### After

```bash
deco@deco-mbp typeschema % yarn ts-node src/__tests__/benchmarks/typebox.ts
yarn run v1.22.19
$ /Users/deco/typeschema/node_modules/.bin/ts-node src/__tests__/benchmarks/typebox.ts
Running "typebox with valid data" suite...
Progress: 100%

  directly:
    6 019 929 ops/s, ±0.43%    | slowest, 41.66% slower

  through TypeSchema:
    10 319 214 ops/s, ±5.57%   | fastest

Running "typebox with invalid data" suite...
Progress: 100%

  directly:
    5 808 129 ops/s, ±1.52%    | slowest, 50.46% slower

  through TypeSchema:
    11 725 064 ops/s, ±0.73%   | fastest

✨  Done in 25.42s.
```

("directly" here means calling `Value.Check()` without going through TypeSchema)

**Comment by sinclairzx81** [comment]
@decs Good work :)
