### ISSUE TITLE
Add support for valibot

### ISSUE THREAD

**Issue by ciscoheat** [decs/typeschema#11]
[Valibot](https://www.builder.io/blog/introducing-valibot) seems like a good addition to typeschema. It has a simple adapter, mentioned here: https://github.com/fabian-hiller/valibot/issues/8

**Comment by decs** [comment]
thanks for the flag, @ciscoheat! done!

**Comment by fabian-hiller** [comment]
Feel free to add TypeSchema to our ecosystem page: https://valibot.dev/guides/ecosystem/
