### ISSUE TITLE
Error: Missing adapters for schema: [object Object]

### ISSUE THREAD

**Issue by sillvva** [decs/typeschema#12]
I am using valibot in a Svelte app. Using `"@decs/typeschema": "^0.7.0"` and `"valibot": "^0.8.0"`

Not getting a type error, but I am getting this message as a runtime error. 

```
Error: Missing adapters for schema: [object Object]
```

Example: 

```typescript
// valibot schema
export const newCharacterSchema = object({
	name: string([minLength(1, "Required")]),
	campaign: string([minLength(1, "Required")]),
	race: useDefault(string(), ""),
	class: useDefault(string(), ""),
	character_sheet_url: useDefault(string([url()]), ""),
	image_url: useDefault(string([url()]), "")
});
```

```html
<!-- +page.svelte -->
<SchemaForm ... schema={newCharacterSchema} ...>
	...
</SchemaForm>
```

```html
<!-- SchemaForm.svelte -->
<script lang="ts" generics="TSchema extends Schema">
import type { Infer, InferIn, Schema } from "@decs/typeschema";
import { validate } from "@decs/typeschema";
	
export let schema: TSchema;
export let data: InferIn<TSchema>;
export let validatedData: Infer<TSchema> | undefined = undefined;

export let errors = new SvelteMap<string, string>();
$: checkErrors(data);

function checkErrors(data: InferIn<TSchema>) {
	errors = errors.clear();
	validate(schema, data).then((result) => {
		if ("issues" in result) {
			result.issues.forEach((issue) => {
				if (issue.path) errors = errors.set(issue.path.join("."), issue.message);
			});
		}
		if ("data" in result) {
			validatedData = result.data;
		}
	});
}
</script>
```

What am I doing wrong?

**Comment by sillvva** [comment]
I also tried passing the schema directly to the `validate` function in `<SchemaForm>` to see what would happen.

```typescript
validate(newCharacterSchema, data)

/*
const newCharacterSchema: ObjectSchema<{
    name: StringSchema<string>;
    campaign: StringSchema<string>;
    race: StringSchema<string>;
    class: StringSchema<string>;
    character_sheet_url: StringSchema<...>;
    image_url: StringSchema<...>;
}, {
    ...;
}>
*/
```

I still get the same error. Seems like the `validate` function does not accept valibot schema functions.

**Comment by sillvva** [comment]
Looks like it works on the server, but not on the client.

```typescript
// SchemaForm.svelte
validate(schema, {}).then(console.log);
```

<img width="388" alt="CleanShot 2023-08-05 at 07 09 50@2x" src="https://github.com/decs/typeschema/assets/5138384/9c20d16b-8f37-431e-adf5-cb635cf8351a">
<img width="526" alt="CleanShot 2023-08-05 at 07 10 07@2x" src="https://github.com/decs/typeschema/assets/5138384/f87e4e87-7d0c-4d11-8bb6-545d3a35a70f">

**Comment by decs** [comment]
hey, @sillvva! I refactored the adapter registry with the new version (v0.8.2). I'm not very familiar with Svelte, but I tried it and it seems it's now working. though I apparently needed to add some of the optional peer dependencies to `build.rollupOptions.external` to allow for building the app. Could you help further test it? Thanks!!

**Comment by decs** [comment]
It seems to be related to Vite's bundling https://github.com/vitejs/vite/issues/6007

**Comment by sillvva** [comment]
Yeah, I get this error now:

```
[vite] error while updating dependencies:
Error: Build failed with 2 errors:
node_modules/.pnpm/@decs+typeschema@0.8.2_valibot@0.8.0/node_modules/@decs/typeschema/dist/io-ts-BRWJAQV3.mjs:2:24: ERROR: Could not resolve "fp-ts/Either"
node_modules/.pnpm/@decs+typeschema@0.8.2_valibot@0.8.0/node_modules/@decs/typeschema/dist/typebox-WF7VWWUM.mjs:2:29: ERROR: Could not resolve "@sinclair/typebox/compiler"
    at failureErrorWithLog (/Users/sillvva/Projects/ddal-svelte/node_modules/.pnpm/esbuild@0.18.11/node_modules/esbuild/lib/main.js:1639:15)
    at /Users/sillvva/Projects/ddal-svelte/node_modules/.pnpm/esbuild@0.18.11/node_modules/esbuild/lib/main.js:1051:25
    at /Users/sillvva/Projects/ddal-svelte/node_modules/.pnpm/esbuild@0.18.11/node_modules/esbuild/lib/main.js:1515:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Could you explain what I need to add to the vite config?

**Comment by sillvva** [comment]
I managed to get it to build with `external: ["@decs/typeschema", "fp-ts", "fp-ts/Either"]`, but then I get this when running it:

<img width="472" alt="CleanShot 2023-08-11 at 09 03 14@2x" src="https://github.com/decs/typeschema/assets/5138384/e211fad6-1144-43bf-b5f0-4f483546f037">

**Comment by decs** [comment]
Solved! I wrapped the handling logic into a Vite plugin in `v0.9.1`, which can be easily plugged in your `vite.config.ts`:

```ts
import { typeschemaPlugin } from "@decs/typeschema/vite";

export default defineConfig({
  plugins: [
    typeschemaPlugin(), // add this plugin
  ],
});
```

If you're still seeing an error, feel free to open another issue and I can take a look. Thanks for the feedback!

**Comment by sillvva** [comment]
Perfect!
