### ISSUE TITLE
We will change the `safeParseAsync` API of Valibot

### ISSUE THREAD

**Issue by fabian-hiller** [decs/typeschema#14]
This is just a hint that we will change the `safeParseAsync` API. You can write `result.issues` in the next version instead of `result.error.issues`. `.error` will still work then but is deprecated.

https://github.com/decs/typeschema/blob/main/src/adapters/valibot.ts#L35

**Comment by decs** [comment]
Thanks for the heads up!! I'll update it once the next version is out

**Comment by fabian-hiller** [comment]
I'll write you here as soon as the version is available.

**Comment by fabian-hiller** [comment]
The new version v0.13.0 is available.

**Comment by decs** [comment]
upgraded!
