### ISSUE TITLE
Support for class validator

### ISSUE THREAD

**Issue by niemyjski** [decs/typeschema#26]
https://github.com/typestack/class-validator

**Comment by niemyjski** [comment]
Is this project still maintained?

**Comment by niemyjski** [comment]
@decs what would one need to do to support this?

**Comment by decs** [comment]
I was focusing all my time on the package restructure (#32). now that it's done, we have a better foundation to support more validation libraries 😃 I'm open to accepting PRs or I can make some time to implement this within the next week

**Comment by niemyjski** [comment]
I don't have much time in the next two weeks to dig in, but I could help test.

**Comment by decs** [comment]
done! this is launched as [@typeschema/class-validator](https://www.npmjs.com/package/@typeschema/class-validator)

**Comment by niemyjski** [comment]
Thank you so much!!!!!
