### ISSUE TITLE
Add JSON Schema export to the API?

### ISSUE THREAD

**Issue by ciscoheat** [decs/typeschema#27]
Now that its decided that TypeSchema [will be used in Superforms v2](https://blog.encodeart.dev/superforms-v2-supporting-all-validation-libraries#heading-problem-3-introspection), I'm seeing the need for a Validation Schema to JSON Schema feature for the validation libraries. 

I'm planning to do this with similar kind adapters as in TypeSchema, but then I was thinking "why shouldn't that be a part of TypeSchema, or its own library?" So I wonder if it would be feasible to build this into TypeSchema? Of course, I'll be contributing to that feature.

**Comment by dmdin** [comment]
I also need this feature to generate an OpenRPC specification from I/O validators with support of multiple validator libraries ☺️

**Comment by decs** [comment]
Released as part of `v0.13.0`. There's now a `toJSONSchema` function. Let's work on making all adapters compatible!
