### ISSUE TITLE
Proposal: common set schema api 

### ISSUE THREAD

**Issue by Talent30** [decs/typeschema#30]
Hi, Thank you for this lib.

It would be nice if we can abstract a common set of schema apis (e.g. merge schemas) available for lib authors.

I am happy to help implementing this if you think this is a valid requirement.

**Comment by decs** [comment]
Hi, @Talent30! Thanks for the feedback!

Do you mean merging object schemas  of different libraries into one? Or just offering more methods than just validation?

On the latter, I've been doing a major refactor (under the `monorepo` branch) that will unblock adding methods that work with just a subset of validation libs. My expectation is to publish  it in 2 weeks.

**Comment by decs** [comment]
Solved as part of `v0.13.0`
