### ISSUE TITLE
Schema is wrongly typed for schemas having output!=input

### ISSUE THREAD

**Issue by ecyrbe** [decs/typeschema#5]
Hello,
  
I did some tests on some more advanced schemas.  
  
There are some issues with current approach to infer the type for libraries supporting inputs that are different than outputs.
For example, in arktype, adding transformations, the type T of the schema is not equal the typescript type to output :
![image](https://github.com/decs/typeschema/assets/633115/3774ab3d-0c3d-470b-9877-9f0b3a136f83)

There is the same kind of issue with `io-ts` where the schema inferred is wrong and can't even be passed to `validate` function when transforming the input data to a different one (example transforming a `string` to a `Date` object)

One solution is to remove the utility type `Schema<T>` and instead change the signature of `validate` and `assert` functions.
```ts
export async function validate<Schema>(
  schema: Schema,
  data: unknown,
): Promise<{data: InferOutput<Schema>} | {issues: Array<ValidationIssue>}> {
  const wrappedSchema = wrapCached(schema) ?? (await wrap(schema));
  return wrappedSchema.validate(data);
}
```
and:
```ts
export async function assert<Schema>(schema: Schema, data: unknown): Promise<InferOutput<Schema>> {
  const result = await validate(schema, data);
  if ('issues' in result) {
    throw result.issues[0];
  }
  return result.data;
}
```

I'm creating a PR to solve this in this way.
It will be a **BREAKING CHANGE**. Since you'll no more have `Schema<T>` type.
But i don't thing it's that bad, since nobody should use this utility type directly, because you don't want to write the ts type youself but always want to infer it.

**Comment by decs** [comment]
That's a great catch!

I'm wary of adding more `any`s to the code and/or making the integrator-facing API more complex. so I'd like some time to explore possibly less disruptive solutions, if any exist

I'm slower to respond this week since I'm out on vacation. So I'm hoping to get more time to invest on this next weekend

**Comment by decs** [comment]
Merged!
