### ISSUE TITLE
Valibot v33

### ISSUE THREAD

**Issue by kaeon** [decs/typeschema#60]
Valibot is moving rapidly and while there is a fix now for v31, upgrading to v33 breaks npm install. Is there a way to allow new versions and still use @typeschema/valibot?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/decs) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/decs/typeschema/issues/60">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/decs/typeschema/issues/60/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/decs/typeschema/issues/60/pledge.svg">
</picture>
</a>

**Comment by fabian-hiller** [comment]
Yes, unfortunately I introduced a breaking type change in v0.33.0. Therefore it is necessary to update Valibot and all related dependencies.

**Comment by decs** [comment]
Done! Updated to `v0.39.0`
