### ISSUE TITLE
@typeschema/main doesn't infer the type of zod object correctly

### ISSUE THREAD

**Issue by Melvynx** [decs/typeschema#63]
Today I try this code : 

```ts
import { Infer, Schema } from '@typeschema/main';

const ZodSchema = z.object({
  title: z.string(),
});

type ZodSchemaType = z.infer<typeof ZodSchema>;

type Output = Infer<typeof ZodSchema>;
```

![CleanShot 2024-08-06 at 22 04 52](https://github.com/user-attachments/assets/1e7af1f0-d377-401f-8c7f-2170c3a129e3)

But the type of `output` is any, when I replace `@typeschema/main` by `@typeschema/zod` the error is fixed.

The documentation is very small, is this a feature or a bug ?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/decs) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/decs/typeschema/issues/63">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/decs/typeschema/issues/63/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/decs/typeschema/issues/63/pledge.svg">
</picture>
</a>

**Comment by sebastianwessel** [comment]
Same issue and it is kind of blocking development @puristajs

Hope, it gets solved soon

**Comment by sebastianwessel** [comment]
Seems not to be zod specific:

```ts
import type { Infer } from "@typeschema/main";
import {object,string} from 'yup'

const yupSchema = object({ 
  optionOne: string().required()
})


type test= Infer<typeof yupSchema>
// test = unknown
```

**Comment by sebastianwessel** [comment]
@decs 

The root cause of this issue is, that the lib is using `@sinclair/typebox`, which is missing in the package dependencies.

Without this dependency, `IsTypeboxSchema` returns true, even if it is a zod or yup schema, which results in a wrong `Select` with `typebox` instead of `zod` or `yup`.

```typescript
export type Select<TSchema> =
  // eslint-disable-next-line @typescript-eslint/no-unsafe-function-type
  TSchema extends Function
    ? TSchema extends {assert: unknown} ? 'arktype'
    : IsEffectSchema<TSchema> extends true ? 'effect'
    : IsClassValidatorSchema<TSchema> extends true ? 'classValidator'
    : 'function'
  : TSchema extends object
    ? IsTypeboxSchema<TSchema> extends true ? 'typebox'
    : IsSuretypeSchema<TSchema> extends true ? 'suretype'
    : TSchema extends {__isYupSchema__: unknown} ? 'yup'
    : TSchema extends {_def: unknown} ? 'zod'
    : TSchema extends {async: unknown} ? 'valibot'
    : TSchema extends {refiner: unknown} ? 'superstruct'
    : TSchema extends {_flags: unknown} ? 'joi'
    : TSchema extends {encode: unknown} ? 'ioTs'
    : TSchema extends {reflect: unknown} ? 'runtypes'
    : TSchema extends {kind: unknown} ? 'deepkit'
    : TSchema extends {addValidator: unknown} ? 'ow'
    : TSchema extends {toTerminals: unknown} ? 'valita'
    : TSchema extends {bail: unknown} ? 'vine'
    : IsJSONSchema<TSchema> extends true ? 'json'
    : 'fastestValidator'
  : never;
```

@Melvynx 
The temporary workaround/fix is, to manually add the missing dep.
`npm i -D @sinclair/typebox`

**Comment by meslzy** [comment]
+1 here, its blocking our progress

```ts
import { InferIn } from "@typeschema/main";
import { z } from "zod";

const schema = z.object({
  name: z.string(),
});

type SchemaInput = InferIn<schema>;
//    ? type SchemaInput = unknown
```

**Comment by nlfmt** [comment]
+1, for some reason im only getting the error when running tsc to lint, in vscode all types are correctly inferred. Installing `@sinclair/typebox` fixes that, but it's not a desirable workaround for libraries.

**Comment by decs** [comment]
solved, thanks @nlfmt for the fix!

**Comment by Melvynx** [comment]
thanks !
